services:
  app:
    container_name: toyproject-team5
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      # 1. DB 설정
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: toyproject-team5
      DB_USER: waffle
      DB_PASSWORD: somepassword

      # 2. Redis 설정
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # 3. 기타 설정
      JWT_SECRET: "secret-key-for-local-development-only"
      S3_BUCKET_NAME: "dummy-bucket"

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: toyproject-team5
      MYSQL_ROOT_PASSWORD: root

      MYSQL_USER: waffle
      MYSQL_PASSWORD: somepassword

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"