spring:
  profiles:
    active: dev

  application:
    name: studygroup

  cloud:
    aws:
      region:
        static: ap-northeast-2
      stack:
        enabled: false

  jackson:
    property-naming-strategy: SNAKE_CASE # 안드로이드와 통신 시 스네이크 케이스 권장
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET:your_default_dev_secret_key_more_than_32_characters}
  expiration-time: 604800000

server:
  forward-headers-strategy: native