apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-app
  labels:
    app: team5-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team5-app
  template:
    metadata:
      labels:
        app: team5-app
    spec:
      containers:
        - name: team5-app
          image: ghcr.io/wafflestudio/23-5-team5-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: PROD_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secret
                  key: PROD_GOOGLE_CLIENT_ID

            - name: PROD_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth-secret
                  key: PROD_GOOGLE_CLIENT_SECRET


            # frontend 측에서도 swagger 볼 수 있도록
            - name: SPRINGDOC_SWAGGER_UI_ENABLED
              value: "true"
            - name: SPRINGDOC_API_DOCS_ENABLED
              value: "true"

            # 아래 두 개는 현재 table이 없어서 임시방편으로 작성함
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            # 나중에 마지막에 배포할 때 주석처리


            # --- DB 접속 정보 ---
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "toyproject-team5"
            - name: DB_USER
              value: "waffle"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: team5-secrets
                  key: mysql-user-password

            # --- Redis 접속 정보 ---
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

            # --- 보안 키 (JWT) ---
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: team5-secrets
                  key: jwt-secret

            # --- S3 Bucket ---
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: team5-config
                  key: S3_BUCKET_NAME

            # --- Region ---
            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: AWS_DEFAULT_REGION
              value: "ap-northeast-2"

            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mail-config
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: MAIL_PASSWORD