apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-app
  labels:
    app: team5-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team5-app
  template:
    metadata:
      labels:
        app: team5-app
    spec:
      containers:
        - name: team5-app
          image: ghcr.io/wafflestudio/23-5-team5-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # --- DB 접속 정보 ---
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "toyproject-team5"
            - name: DB_USER
              value: "waffle"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: team5-secrets
                  key: mysql-user-password

            # --- Redis 접속 정보 ---
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

            - name: AWS_REGION
              value: "ap-northeast-2"
            - name: S3_BUCKET_NAME
              value: "team5-s3-bucket" # 실제 버킷명으로 수정 #TODO
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: team5-secrets
                  key: aws-access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: team5-secrets
                  key: aws-secret-key

            # --- 보안 키 (JWT) ---
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: team5-secrets
                  key: jwt-secret